---
title: "Dunaets Research"
subtitle: "Data Manipulation"
author: 
  - name: "Alona Nazarenko"
    email: [alionanazarenko155@gmail.com]
    affiliations: ["Kyiv School of Economics"]
format:
  html: 
    highlight-style: github
    theme: [default, custom.scss]
---

```{python}
#| label: libraries
#| include: false
#| message: false
import numpy as np
import pandas as pd
import altair as alt
from transliterate import translit
```


## Main Research Topics

1. **Preservation of Surnames and Changes in Their Number (1778–1897)**  
   Analysis of the dynamics of surname counts in the village of Dunayets and their preservation over more than a century.

2. **Gender-Age Pyramids (1778 and 1897)**  
   Construction and comparison of the age-sex structures of the population in two historical periods.

3. **Literacy and Types of Educational Institutions (1897)**  
   Study of literacy levels among different social statuses of the population and the types of educational institutions where they received their education.

#### Data Preparation

1. Reading data from CSV  
2. Renaming columns for easier use  
3. Removing empty rows  
4. Filling the surname column in 1778

```{python}
people_1897 = pd.read_csv("2.1_Дунаєць.xlsx - База людей.csv")
people_1778 = pd.read_csv("2.2_Дунаєць_1778.xlsx - База.csv", header=3)
# church_1778 = pd.read_csv("2.2_Дунаєць_1778.xlsx - Пояснення та фінальні таблиці.csv")

people_1897 = people_1897.drop(['Кто заполнял базу', 'ID строки в базе', 'List ID', 'Link'], axis = 1)
people_1897.columns = ['ID_housekeeping', 'ID_person', 'full_name', 'sex',
                       'family_status', 'age', 'marriage status', 'social_status', 
                       'born_here', 'place_of_birth', 'assigned_here',
                      'live_here', 'mark_of_absence', 'religion', 
                      'native_language', 'ability_of_reading', 'education',
                      'main_profession', 'side_profession', 'conscription',
                      'notes']
people_1778 = people_1778.drop(['Unnamed: 0', 'Двори джерело'], axis = 1)
people_1778.columns = ['ID_person', 'ID_housekeeping', 'm_num_unique',
                       'f_num_unique', 'm_num_resource', 'f_num_resource',
                      'name', 'patronymic', 'surname', 'family_status',
                      'family_category', 'family_class', 'social_status',
                      'age', 'was_on_confession', 'was_not_on_confession',
                      'underage_absence']
people_1897 = people_1897[people_1897.ID_housekeeping.notna()]
people_1778.surname = people_1778.surname.ffill()
```

---

## Preservation of Surnames and Changes in Their Number (1778–1897) in the Village of Dunayets

#### Transliteration

Since one of the databases is provided in English, I first transliterate the surnames into Ukrainian using the `transliterate` library.  
In addition, I perform transliteration into Russian, as the second database is recorded in the language used at the time — Old Ukrainian. In it, some surnames are documented with letters characteristic of the Russian alphabet.

After that, I split the data into columns with surnames for further processing.

```{python}
people_1897[['surname_uk', 'name_uk', 'patronymic_uk']] = people_1897.full_name.str.split(' ', n=2, expand=True)\
  .map(lambda x: translit(x, 'uk') if pd.notnull(x) else x)   
people_1897['surname_ru'] = people_1897.full_name.str.split(' ', n=1)\
    .str[0].map(lambda x: translit(x, 'ru') if pd.notnull(x) else x)
```

#### Extracting the Root of Surnames in the 1897 Census

To count all people with the same surname in 1897, where surnames differed formally (due to declension), I try to extract the **root of the word** by removing the most common and grammatically similar (transliterated) **suffixes** and **endings**.

This is done in **two stages**:  
1. Using **regular expressions**.  
2. Through additional processing of **individual cases**.


```{python}
people_1897['root_surname'] = people_1897.surname_uk.str.replace("(?:енко|ський|ській|йова|ін|інова|іcкій|ськаиа|скій|укова|скаиа|ова|ева|еев|аиа|еева|ськ|укова|ов|ович|івна|іна|ей|ин|а|я|уков|ій|ий|иа|)$", '', regex=True)
people_1897['rootsurname'] = people_1897.root_surname.str.replace("(?:ук|юк|чук|иш|ів|ов|ськ|як|ець|ан|ар|ин|ев|ін)$", '', regex=True)
people_1897.loc[people_1897.root_surname == 'Дручк', 'root_surname'] = 'Дручок'
people_1897.loc[people_1897.root_surname == 'Козл', 'root_surname'] = 'Козел'
people_1897.loc[people_1897.root_surname == 'Рожн', 'root_surname'] = 'Рожен'
people_1897.loc[people_1897.root_surname == 'Овсеенк', 'root_surname'] = 'Овсе'
people_1897.loc[people_1897.root_surname == 'КулЬбак', 'root_surname'] = 'Кулібак'
people_1897.loc[people_1897.root_surname == 'Бабіч', 'root_surname'] = 'Бабич'
people_1897.loc[people_1897.root_surname == 'Науменк', 'root_surname'] = 'Наум'
people_1897.loc[people_1897.root_surname == 'Савіcк', 'root_surname'] = 'Сав'
people_1897.loc[people_1897.root_surname == 'Старченк', 'root_surname'] = 'Старч'
people_1897.loc[people_1897.root_surname == 'Тішченк', 'root_surname'] = 'Тішч'
people_1897.loc[people_1897.root_surname == 'Ґайдук', 'root_surname'] = 'Ґайд'
people_1897.loc[(people_1897.root_surname == 'Мехедок')|(people_1897.root_surname == 'Мехедк'), 'root_surname'] = 'Мехед'
people_1897.loc[(people_1897.root_surname == 'Божок')|(people_1897.root_surname == 'Божк'), 'root_surname'] = 'Бож'
people_1897.loc[(people_1897.root_surname == 'Воро')|(people_1897.root_surname == 'ВоробЬ'), 'root_surname'] = 'Вороб'
people_1897.loc[(people_1897.root_surname == 'Малафеенк')|(people_1897.root_surname == 'Малофе'), 'root_surname'] = 'Малафе'
```

I define a **list** of common **surnames**, create a corresponding list of their **"roots"**, and build a **dictionary** mapping roots to surnames.

```{python}
surnames = list((set(people_1897.surname_ru.unique()) & set(people_1778.surname.unique())) \
                | (set(people_1897.surname_uk.unique()) & set(people_1778.surname.unique())))

surname_df_uk = people_1897.loc[people_1897.surname_uk.isin(surnames), ['surname_uk', 'root_surname']]
surname_df_ru = people_1897.loc[people_1897.surname_ru.isin(surnames), ['surname_ru', 'root_surname']]
root_to_surname = dict(surname_df_uk.drop_duplicates().set_index('root_surname')['surname_uk'])
root_to_surname.update(
    dict(surname_df_ru.drop_duplicates().set_index('root_surname')['surname_ru'])
)

root_list = list(root_to_surname.keys())
```

I count the number of people with each surname separately for 1778 and 1897.  
To do this, I filter the data by the list of surnames or surname roots, group by surname, and count the number of unique individuals.

After counting for each year, I add a `group` column indicating the year, and combine both results into a single dataframe.

I also calculate the difference between the number of people in 1897 and 1778 and add it to the combined dataframe.

```{python}
amount_surnames_1778 = people_1778[people_1778.surname.isin(surnames)]\
    .groupby('surname').agg(amount_of_people = ('ID_person', 'count')).reset_index()
amount_surnames_1897 = people_1897[people_1897.root_surname.isin(root_list)]\
    .groupby('root_surname').agg(amount_of_people = ('ID_person', 'count')).reset_index()\
    .rename(columns={'root_surname': 'surname'})
amount_surnames_1897.surname = amount_surnames_1897.surname.map(root_to_surname)
amount_surnames_1778['group'] = '1778'
amount_surnames_1897['group'] = '1897'

diff_df = amount_surnames_1778.merge(amount_surnames_1897, on='surname')
diff_df['diff'] = (diff_df.amount_of_people_y - diff_df.amount_of_people_x)

combined = pd.concat([amount_surnames_1778, amount_surnames_1897], ignore_index=True)
combined = combined.merge(diff_df[['surname', 'diff']], how='left')
combined['diff'] = combined['diff'].apply(lambda x: f"+{x}" if x > 0 else f"{x}")
```

## Bar Chart

```{python}
#| code-fold: true
sorted_surnames = combined[combined.group == '1897'].sort_values(
    by='amount_of_people', ascending=True
)['surname'].tolist()

surname_chart = alt.Chart(combined).mark_bar().encode(
    x=alt.X(
        'surname:N', 
        title= "Surname", 
        axis=alt.Axis(labelAngle=45),
        sort=sorted_surnames
           ),
    y=alt.Y('amount_of_people:Q', title='Amount'),
    color=alt.Color('group:N', scale=alt.Scale(scheme='viridis'), title="Year"),
    xOffset="group:N",
    tooltip= [
    alt.Tooltip('surname:N', title='Surname'),
    alt.Tooltip('amount_of_people:Q', title='Amount of People'),
    alt.Tooltip('diff:N', title='Difference')  
]
).properties(
    title='Comparison of People with the Same Surname in Dunaets (1778 vs. 1897)',
    width=800,
).interactive()

surname_chart
```
---
## Age-Sex Pyramids for 1778 and 1897 in the Village of Dunayets

### Data Preparation

Since the 1778 data does not have a separate column indicating sex, I created a new `sex` column based on one of the existing columns that allows determining whether a person is male or female. This column will be used for further analysis.

```{python}
people_1778['sex'] = np.where(
    people_1778['m_num_unique'].notna(), 'm', 'f'
)
```

In addition, the 1897 data has an issue with accurately determining age, as some records contain values like `6 month`, `2 week`, `1.5`, etc.

Since I will be creating an age-sex pyramid with 5-year age intervals, the exact number of days or months for a child — 6 months or 2 weeks — is not significant; in any case, it is less than one year. Therefore, I assign a value of `0` to such records.

To avoid ambiguities with incomplete numeric values (e.g., `1.5`), I round all age values to whole numbers and use the `Int8` data type. This is possible because the dataset does not include people older than 127 years — i.e., there are no cases exceeding the limits of this data type.

```{python}
people_1897['age'] = np.where(
    people_1897['age'].astype(str).str.contains('month|week|day|less'),
    0,
    pd.to_numeric(people_1897['age'], errors='coerce').round().astype('Int8')
)

```

Since I will be creating two pyramids, I don't want to duplicate code with the same structure for each of them. Therefore, I decided to extract the repeated logic into a separate function for plotting the graph.


```{python}
def Population_Pyramid_graph(df : pd.DataFrame, year):
    base = alt.Chart(df)
    
    color_scale = alt.Scale(domain=['m', 'f'],
                            range=['#1f77b4', '#e377c2'])
    
    left = base.transform_filter(
        alt.datum.sex == 'f'
    ).mark_bar().encode(
        y=alt.Y('age:Q', 
                axis=None, 
                bin=alt.Bin(step=5),
               scale=alt.Scale(domain=(0, 90))
               ),
        x=alt.X('count(ID_person):Q',
                title='population',
                sort=alt.SortOrder('descending'),
                scale=alt.Scale(domain=(0, 170)),
               ),
        color=alt.Color('sex:N', scale=color_scale, 
                        legend=None
                       ),
        tooltip = alt.Tooltip(['count(ID_person)'])
    ).properties(
        title=alt.Title('Female', font=font_text, fontSize = 16),
        height = 360,
        width=200
    )+ alt.Chart(pd.DataFrame({'text': [str(year)]})).mark_text(
    x=50,
    y=30,
    fontSize=20,
        font=font_text
).encode(
    text='text:N'
)

    bins = np.arange(90, -5, -5)
    labels = [f"{bins[i+1]}-{bins[i]}" for i in range(len(bins)-1)]
    interval_df = pd.DataFrame({
        'Range': labels
    })
    
    middle = alt.Chart(interval_df).mark_text().encode(
        y=alt.Y('Range:N', axis=None, sort=labels),
        text='Range'
    ).properties(width=40)
    
    right = base.transform_filter(
        alt.datum.sex == 'm'
    ).encode(
        y=alt.Y(
            'age:Q', 
            bin=alt.Bin(step=5), 
                axis=None
               ),
        x=alt.X(
            'count(ID_person):Q',
            title='population', 
            scale=alt.Scale(domain=(0, 130)), 
        ),
        tooltip = alt.Tooltip(['count(ID_person)']),
        color=alt.Color('sex:N', scale=color_scale, legend=None)
    ).mark_bar().properties(
        title = alt.Title('Male', font=font_text, fontSize = 16),
        height = 360,
        width=200
    )
    
    return alt.concat(left, middle, right, spacing=5)
```

## Age-Sex Pyramids

First, I select the necessary data from each dataframe, remove records with unknown age, and then plot the graph.


```{python}
age_df_1897 = people_1897[['sex', 'age', 'ID_person']].dropna(subset=['age'])
age_df_1778 = people_1778[['sex', 'age', 'ID_person']].dropna(subset=['age'])
font_text = 'Arial'

population_1778 = Population_Pyramid_graph(age_df_1778, '1778')
population_1897 = Population_Pyramid_graph(age_df_1897, '1897')
alt.concat(population_1778, population_1897, spacing=40).properties(
    title = alt.Title('Dunaets Population Pyramid for the Period 1778–1897',
                      anchor='middle', 
                      fontSize=20,
                      offset=20,
                      font= font_text
                     )
)

```

----
## Literacy and Types of Educational Institutions for Different Social Statuses in 1897 in the Village of Dunayets

First, I examine the overall literacy statistics among the population, then filter the data by removing rows without information on literacy. After that, I count the total number and create the corresponding dataframe.

To make the chart legend clear, I replace the binary representation with descriptive labels. In addition, to display percentage ratios, I create a new `percentage` column.

```{python}
people_1897.ability_of_reading.describe()
```

```{python}
reading_counts = people_1897['ability_of_reading'].dropna().value_counts().reset_index()
reading_counts = reading_counts.sort_values(by='ability_of_reading',  ascending=False).reset_index()
reading_counts.ability_of_reading = reading_counts.ability_of_reading.map({
    0.0 : 'Cannot read',
    1.0 : 'Can read'
})
reading_counts['percentage'] = np.round((reading_counts['count']/ reading_counts['count'].sum()), 1) 
reading_counts['theta'] = reading_counts['percentage'] * 1000
```

## Literacy Donut Chart

```{python}
#| code-fold: true
base_arc = alt.Chart(reading_counts).mark_arc(innerRadius=70).encode(
    theta=alt.Theta(field='count', type='quantitative'),
    color=alt.Color(field='ability_of_reading',
                    type='nominal',
                    scale= alt.Scale(range=['#0d5b11', '#8DC71E']), 
                    legend=alt.Legend(title='Reading Ability')
                   ),
    tooltip= [alt.Tooltip('ability_of_reading', title="Ability of Reading"),
              alt.Tooltip('count')]
)

text_layer = alt.Chart(reading_counts).mark_text(
    radius=100,
    fontSize = 21
).encode(
    text = alt.Text('percentage', format=".0%"),
    theta=alt.Theta('theta', type='quantitative'),
    color= alt.Color('index:Q',
                     scale=alt.Scale(
                         domain = [0,1],
                         range=['#0d5b11', '#8DC71E'] 
                     ),
                     legend=None
                    )
)

reading_chart = (base_arc + text_layer).properties(
    title=alt.Title('Reading Ability Distribution in 1897', fontSize= 18, offset = 20, dx = 50)
)
reading_chart
```

#### Extracting Data for the Second Chart

To build the second chart, I select and filter the data containing information about:

- **Social status of the population** (`social_status`)  
- **Place where people were educated** (`education`)

These data are needed to analyze the relationship between social status and the type of educational institution where people received their education.  
The goal is to show the **number of people in each social status** depending on the **place of education**.


```{python}
education_status = people_1897[['education', 'social_status']]
education_status = education_status.dropna(subset=['education'])
education_status.social_status.value_counts()
```


### Categorization of Educational Institutions

Since the data contains **41 unique names of educational institutions**, for better readability, I categorize these names into **7 generalized groups**:

- **Zemstvo school**  
- **Rural school**  
- **Home education**
- **City school**
- **Church education** (education at the church)  
- **Military education** (education in the regiment)  
- **Other** — all other cases that do not fall into any of the previous categories

To do this, I use **regular expressions** to automatically identify keywords and phrases characteristic of each category.

```{python}
condition = [
    education_status.education.str.contains(r'\bzemsk(?:oe|om|aya)', case=False),
    education_status.education.str.contains(r"\b(?:sel's?k(?:[aoe]e?|aya)|sel'skoj|rural)\b", case=False),
    education_status.education.str.contains(r'\b(?:home|doma)\b', case=False),
    education_status.education.str.contains(r'\bgorod(?:skoe|skom)\b', case=False),
    education_status.education.str.contains(r'\b(?:cerkovno[- ]prikhodskaya|u prichetnika|seminariya|umanskoe|Novgorod-Severskaya)\b', case=False),
    education_status.education.str.contains(r'\b(?:v polku)\b', case=False),
]

education_type = [
    'Zemstvo school',
    'Rural school',
    'Home education',
    'City school',
    'Church school',
    'Military education'
]

education_status['category'] = np.select(condition, education_type, default='Others')
```

#### Simplifying Social Statuses

In addition to the main analysis, I also reduced the number of unique social statuses, as some of them have similar social or economic positions and can be grouped into generalized categories.

The grouping is done as follows:

- **Peasant**:  
  - `peasant-owner` and `state peasant` were combined, as both groups belonged to the rural population that owned or worked the land, regardless of the form of ownership.

- **Noble**:  
  - `nobles` and `imenuyushchijsya dvoryanin` share a privileged social status, placing them in the noble class.

This grouping helps avoid excessive detail, reduces the number of categories, and better represents overall social trends in the visualization.


```{python}
education_status.social_status = education_status.social_status.map({
    'cossack': 'Cossack',
    'peasant-owner': 'Peasant',
    'state peasant': 'Peasant',
    'dukhovnogo': 'Clergy',
    'imenuyushchijsya dvoryanin': 'Noble',
    'nobles': 'Noble',
    'citizen': 'Urban resident',
    'dvorovyj': 'Servant'
})
```

### Chart: "Literacy Rates Across Different Social Classes in 1897"

```{python}
#| code-fold: true
ed_df = education_status.social_status.value_counts().reset_index()
ed_df['percentage'] = np.round((ed_df['count']/ ed_df['count'].sum()), 1) 
ed_df['status'] = ed_df.social_status.copy()
ed_char = alt.Chart(ed_df).mark_arc(innerRadius=70).encode(
    theta=alt.Theta(field='count', type='quantitative'),
    color=alt.Color(field='status',
                    type='nominal',
                    scale= alt.Scale(scheme='tableau10'), 
                    legend=alt.Legend(title='Social Status')
                   ),
    tooltip= [alt.Tooltip('status', title="Status"),
              alt.Tooltip('count')]
).properties(
    title=alt.Title('Social Groups That Received Education in 1897', fontSize= 18, offset = 20, dx = 50)
)
read_ed_char = alt.concat(reading_chart,ed_char,  )
read_ed_char
```

### Chart: "Distribution of Social Statuses by Type of Education"

```{python}
#| code-fold: true
status_list = education_status.social_status.unique().tolist()

ordered_categories = education_status.category.value_counts().index.tolist()

status_color = alt.Scale(
    domain=[
        'Cossack', 'Peasant', 'Clergy', 'Noble',
        'Urban resident', 'Servant', 'Total'
    ],
    range=[
        '#264653', '#2a9d8f', '#e76f51',
        '#ffb703', '#E27396', '#6D9F71', '#dcdcdc'
    ]
)

status_param = alt.param(
    name='status_param',
    bind=alt.binding_select(name='Social Status', options=['All'] + status_list),
    value='All'
)

education_chart = alt.Chart(education_status).encode(
    x=alt.X("count(social_status):Q", title="Number of People")
).properties(width=800, height=200)

total = education_chart.mark_bar(opacity=0.8, color='lightgrey', size=15).encode(
    y=alt.Y("category:N", sort=ordered_categories),
    tooltip=[
        alt.Tooltip("count(social_status):Q", title="Total"),
        alt.Tooltip("category:N", title="Category")
    ]
)


points = education_chart.mark_point(size=100, opacity=1, filled=True).encode(
    y=alt.Y("category:N", sort=ordered_categories, title="Education Type"),
    color=alt.Color("social_status:N", scale=status_color, legend=alt.Legend(title="Social Status")),
    tooltip=[
        alt.Tooltip("social_status:N", title="Status"),
        alt.Tooltip("category:N", title="Education"),
        alt.Tooltip("count():Q", title="Count")
    ]
).transform_filter(
    (alt.datum.social_status == status_param) | (status_param == 'All')
).add_params(
    status_param
).properties(
    title='Distribution of Social Statuses by Type of Education in Dunaets, 1897'
)


(total + points).interactive()

```


